Punkrockviking contribution
briancbarrow/atla-go-backend pull request #2
Opened 2023-03-18 01:31 UTC by punkrockviking

add routes/handlers 
searchCharacterBy...
  -nicknames
  -aliases
  -affiliation
  -nationality
  -profession
  -weapons
  -ethnicity
  -fightingStyle

2023-04-01 15:25 UTC, briancbarrow requested changes

2023-04-01 15:25 UTC, briancbarrow commented on api/routes.go
> +	r.HandleFunc("/api/characters", app.searchCharacterByNicknames).Queries("nicknames", "{nicknamenames}")
small typo in nicknames at the end

2023-04-18 02:48 UTC, punkrockviking commented on api/routes.go
> +	r.HandleFunc("/api/characters", app.searchCharacterByNicknames).Queries("nicknames", "{nicknames}")
nicknames typo fixed

2023-04-18 02:49 UTC, punkrockviking reviewed
Fixed typo

2023-05-16 22:02 UTC, merged